### ISSUE TITLE
[Bug]: Unable to use Inventory example with Demo Data

### ISSUE THREAD

**Issue by netgirard** [opsmill/infrahub-ansible#120]
### Ansible Infrahub Collection version

v1.2.1

### Ansible version

```bash
ansible [core 2.14.17]
  config file = /home/<redacted>/Infrahub-Inventory/ansible.cfg
  configured module search path = ['/home/<redacted>/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/<redacted>/Infrahub-Inventory/.direnv/python-3.11.9/lib/python3.11/site-packages/ansible
  ansible collection location = /home/<redacted>/Infrahub-Inventory/collections
  executable location = /home/<redacted>/Infrahub-Inventory/.direnv/python-3.11.9/bin/ansible
  python version = 3.11.9 (main, Apr  6 2024, 17:59:24) [GCC 9.4.0] (/home/<redacted>/Infrahub-Inventory/.direnv/python-3.11.9/bin/python3.11)
  jinja version = 3.1.4
  libyaml = True
```

### Infrahub version

0.16.0

### Python version

3.11

### Steps to Reproduce

Start demo environment and load with infra schema and data with:
```bash
invoke demo.start
invoke demo.load-infra-schema
invoke demo.load-infra-data
```

Used the "Complete Example" from the inventory documentation:
```yaml
# inventory.yml file in YAML format
# Example command line: ansible-inventory -v --list -i .yml
# Add -vvv to the command to also see the GraphQL query that gets sent in the debug output.
# Add -vvvv to the command to also see the JSON response that comes back in the debug output.

# Minimum required parameters
plugin: opsmill.infrahub.inventory
api_endpoint: http://localhost:8000  # Can be omitted if the INFRAHUB_ADDRESS environment variable is set
token: <redacted>  # Can be omitted if the INFRAHUB_API_TOKEN environment variable is set
timeout: 120

# Complete Example
# This will :
# - Retrieve in the branch "branch1" attributes for the Node Kind "InfraDevice"
# - The attributes wanted for "InfraDevice" are forced with the keyword "include"
# - Create 2 compose variable "hostname" ad "platform" (platform will override the attribute platform retrieved)
# - Create group based on the "site" name

strict: true

branch: main

nodes:
  InfraDevice:
    include:
      - name
      - platform
      - primary_address
      - interfaces
      - site

compose:
  hostname: name
  platform: platform.ansible_network_os

keyed_groups:
  - prefix: site
    key: site.name
```

and run with:
```bash
ansible-inventory -vvvvv --list -i infrahub_inventory.yml
```

### Expected Behavior

I expect to see a valid Ansible inventory reflecting the demo data.  Also expect to see the GraphQL query and responses based on the amount of verbose flags.

### Observed Behavior

With strict set to true, no inventory is returned, and no query or JSON response is returned in the debug out.  Only hint is the following:

```
[WARNING]:  * Failed to parse /home/<redacted>/Infrahub-Inventory/infrahub_inventory.yml with auto plugin: Could not set platform for host atl1-core1: 'str object'
has no attribute 'ansible_network_os'. 'str object' has no attribute 'ansible_network_os'
```

With strict set to false, an inventory is returned, but it does appear to be following any relationships, as most fields are populated with UIDs.  Neither statement in the config using complex objects (platform.ansible_network_os and site.name) appear functional based on the UID being returned instead of the nested data.  Still no query or response included with level 5 verbosity.  
Example host vars:

```json
{
    "_meta": {
        "hostvars": {
            "atl1-core1": {
                "hostname": "atl1-core1",
                "id": "17f494d5-271b-b851-3938-c513fe588b4f",
                "interfaces": [
                    "17f494d5-3247-c11f-393b-c5179baac100",
                    "17f494d5-88ad-e291-3938-c51bbaed6f9f",
                    "17f494d6-80ef-a476-3936-c5167773f3da",
                    "17f494d6-8e47-6e79-3934-c51b00245479",
                    "17f494d6-9a9a-3916-3938-c5115d335683",
                    "17f494d6-a72c-f2da-393b-c512606ca9fe"
                ],
                "name": "atl1-core1",
                "platform": "17f494a1-3815-2da2-393e-c518e51a4eb3",
                "primary_address": "17f494d5-d9bc-0daa-3938-c5149f7dd91c",
                "site": "17f494c8-aecb-3301-393e-c51056fbeac5"
            }
        }
    }
}
```

**Comment by wvandeun** [comment]
Hi @netgirard 

Can you test using the following content for the inventory configuration file?
```yaml
plugin: opsmill.infrahub.inventory
api_endpoint: http://localhost:8000
token: <redacted>
timeout: 120

strict: true

branch: main

nodes:
  InfraDevice:
    include:
      - name
      - site.name
      - primary_address.address
      - platform.ansible_network_os

compose:
  ansible_network_os: platform.ansible_network_os
  ansible_host: primary_address

keyed_groups:
  - prefix: site
    key: site.name
```

It seems that some changes were made in the last update(s) that were not reflected in our documentation.
