### ISSUE TITLE
bug: Inventory doesnt work with 1.1.0+ sdk version

### ISSUE THREAD

**Issue by minitriga** [opsmill/infrahub-ansible#150]
### Ansible Infrahub Collection version

latest installed from git

### Ansible version

```bash
ansible [core 2.18.1]
  config file = None
  configured module search path = ['/root/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /root/.cache/pypoetry/virtualenvs/infrahub-avd-fejzH3S0-py3.11/lib/python3.11/site-packages/ansible
  ansible collection location = /root/.ansible/collections:/usr/share/ansible/collections
  executable location = /root/.cache/pypoetry/virtualenvs/infrahub-avd-fejzH3S0-py3.11/bin/ansible
  python version = 3.11.11 (main, Dec  4 2024, 08:55:07) [GCC 11.4.0] (/root/.cache/pypoetry/virtualenvs/infrahub-avd-fejzH3S0-py3.11/bin/python)
  jinja version = 3.1.5
  libyaml = True
```

```yaml
plugin: opsmill.infrahub.inventory
api_endpoint: http://localhost:8000  # Can be omitted if the INFRAHUB_ADDRESS environment variable is set
token: 06438eb2-8019-4776-878c-0941b1f1d1ec  # Can be omitted if the INFRAHUB_API_TOKEN environment variable is set
strict: true

branch: "testing"

nodes:
  DcimDevice:
    include: 
      - name
```

Error:
```
[WARNING]:  * Failed to parse /root/poc-avd/labs/demo/ansible/inventory.yaml with auto plugin: An error occurred while executing the GraphQL Query {'kind': 'DcimDevice',
'include': ['name'], 'exclude': None, 'filters': None, 'prefetch_relationships': True}
```

### Infrahub version

v1.1.2

### Python version

3.11

### Steps to Reproduce

```bash
ansible [core 2.18.1]
  config file = None
  configured module search path = ['/root/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /root/.cache/pypoetry/virtualenvs/infrahub-avd-fejzH3S0-py3.11/lib/python3.11/site-packages/ansible
  ansible collection location = /root/.ansible/collections:/usr/share/ansible/collections
  executable location = /root/.cache/pypoetry/virtualenvs/infrahub-avd-fejzH3S0-py3.11/bin/ansible
  python version = 3.11.11 (main, Dec  4 2024, 08:55:07) [GCC 11.4.0] (/root/.cache/pypoetry/virtualenvs/infrahub-avd-fejzH3S0-py3.11/bin/python)
  jinja version = 3.1.5
  libyaml = True
```

```yaml
plugin: opsmill.infrahub.inventory
api_endpoint: http://localhost:8000  # Can be omitted if the INFRAHUB_ADDRESS environment variable is set
token: 06438eb2-8019-4776-878c-0941b1f1d1ec  # Can be omitted if the INFRAHUB_API_TOKEN environment variable is set
strict: true

branch: "testing"

nodes:
  DcimDevice:
    include: 
      - name
```

Error:
```
[WARNING]:  * Failed to parse /root/poc-avd/labs/demo/ansible/inventory.yaml with auto plugin: An error occurred while executing the GraphQL Query {'kind': 'DcimDevice',
'include': ['name'], 'exclude': None, 'filters': None, 'prefetch_relationships': True}
```

ansible-inventory -i inventory.yaml --list

### Expected Behavior

I should get a list of nodes back

### Observed Behavior

Error:
```
[WARNING]:  * Failed to parse /root/poc-avd/labs/demo/ansible/inventory.yaml with auto plugin: An error occurred while executing the GraphQL Query {'kind': 'DcimDevice',
'include': ['name'], 'exclude': None, 'filters': None, 'prefetch_relationships': True}
```
