### ISSUE TITLE
[Feature]: Inventory - Be able to request only on attribute on a relationship

### ISSUE THREAD

**Issue by BeArchiTek** [opsmill/infrahub-ansible#73]
### Infrahub version

v0.14.2

### Feature type

Change to existing Plugin

### Proposed functionality

As a user i would like to be able to fine-tuned the host_vars, for that, I would like to have a finer approach in the Inventory to avoid getting all the attributes of a given related_node if I a interested in only one

### Use case

Be able to request only one attribute of a relationship instead of the full object to keep the host_vars cleaner

Example: if you want to get only the `ansible_network_os` attribute in `platform` you could do 
```yaml
plugin: opsmill.infrahub.inventory
api_endpoint: "http://localhost:8000"
token: "{{ lookup('ansible.builtin.env', 'INFRAHUB_API_TOKEN') }}"
timeout: 30

strict: false

nodes:
  InfraDevice:
    include:
      - id
      - name
      - platform.ansible_network_os
 ```
 
 instead of 
 ```yaml
plugin: opsmill.infrahub.inventory
api_endpoint: "http://localhost:8000"
token: "{{ lookup('ansible.builtin.env', 'INFRAHUB_API_TOKEN') }}"
timeout: 30

strict: false

nodes:
  InfraDevice:
    include:
      - id
      - name
      - platform

compose:
  platform: platform.ansible_network_os
```

### External dependencies

none
